title: The Bible Key Vision
description: The Literal Map of the Kingdom Within

# Asset & Processing Config
sass:
  sass_dir: _sass
  style: compressed

include:
  - _includes/head-custom.html

mermaid: true

exclude:
  - Slides/*.slides.md
