title: Bible Key Version
description: Master Structural Index & Interior Map

# Asset & Processing Config
sass:
  sass_dir: _sass
  style: compressed

include:
  - _includes/head-custom.html

mermaid: true

exclude:
  - Slides/*.slides.md
